CREATE TABLE IF NOT EXISTS PACIENTE (
    PAC_ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    PAC_NOME            VARCHAR(100) NOT NULL,
    PAC_CPF             CHAR(11)     NOT NULL,
    PAC_TELEFONE        VARCHAR(20)  NOT NULL,
    PAC_DATANASCIMENTO  DATE         NOT NULL,
    PAC_SEXO            CHAR(1)      NOT NULL, -- m = masculino, f = feminino

    CONSTRAINT UQ_PAC_CPF   UNIQUE (PAC_CPF),
    CONSTRAINT CK_PAC_SEXO  CHECK (PAC_SEXO IN ('m', 'f'))
);

CREATE TABLE IF NOT EXISTS MEDICO (
    MED_ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    MED_NOME            VARCHAR(100) NOT NULL,
    MED_CRM             VARCHAR(20)  NOT NULL,
    MED_ESPECIALIDADE   VARCHAR(100) NOT NULL,
    MED_DATANASCIMENTO  DATE         NOT NULL,
    MED_TELEFONE        VARCHAR(20)  NOT NULL,
    MED_CPF             CHAR(11)     NOT NULL,
    MED_PLANTAOINICIO   TIME         NOT NULL,
    MED_PLANTAOFIM      TIME         NOT NULL,
    MED_SEXO            CHAR(1)      NOT NULL, -- m = masculino, f = feminino

    CONSTRAINT UQ_MED_CRM      UNIQUE (MED_CRM),
    CONSTRAINT UQ_MED_CPF      UNIQUE (MED_CPF),
    CONSTRAINT CK_MED_PLANTAO  CHECK (MED_PLANTAOFIM > MED_PLANTAOINICIO),
    CONSTRAINT CK_MED_SEXO     CHECK (MED_SEXO IN ('m', 'f'))
);

CREATE TABLE IF NOT EXISTS CONSULTA (
    CON_ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    CON_PAC_ID        INTEGER NOT NULL,
    CON_MED_ID        INTEGER NOT NULL,
    CON_DATACONSULTA  DATE    NOT NULL,
    CON_HORAINICIO    TIME    NOT NULL,
    CON_HORAFIM       TIME    NOT NULL,
    CON_STATUS        CHAR(1) NOT NULL DEFAULT 'a', -- a = agendada, r = realizada, c = cancelada

    CONSTRAINT FK_CON_PACIENTE FOREIGN KEY (CON_PAC_ID) REFERENCES PACIENTE (PAC_ID) ON DELETE RESTRICT,
    CONSTRAINT FK_CON_MEDICO   FOREIGN KEY (CON_MED_ID) REFERENCES MEDICO (MED_ID) ON DELETE RESTRICT,
    CONSTRAINT CK_CON_HORARIO  CHECK (CON_HORAFIM > CON_HORAINICIO),
    CONSTRAINT CK_CON_STATUS   CHECK (CON_STATUS IN ('a', 'r', 'c'))
);
